export const EMPLOYEE_LIST = [
  {
    id: 1,
    name: "Alice Johnson",
    department: "Engineering",
    isActive: true,
    isRemote: true,
    isManager: false,
    hasOnboarded: false,
    isFullTime: true,
    email: "alice.johnson@example.com",
  },
  {
    id: 2,
    name: "Bob Smith",
    department: "Engineering",
    isActive: false,
    isRemote: true,
    isManager: false,
    hasOnboarded: true,
    isFullTime: true,
    email: "bob.smith@example.com",
  },
  {
    id: 3,
    name: "Charlie Davis",
    department: "HR",
    isActive: true,
    isRemote: true,
    isManager: true,
    hasOnboarded: true,
    isFullTime: true,
    email: "charlie.davis@example.com",
  },
  {
    id: 4,
    name: "Dana Lee",
    department: "Marketing",
    isActive: false,
    isRemote: true,
    isManager: false,
    hasOnboarded: false,
    isFullTime: false,
    email: "dana.lee@example.com",
  },
  {
    id: 5,
    name: "Ethan Brown",
    department: "Sales",
    isActive: true,
    isRemote: false,
    isManager: true,
    hasOnboarded: false,
    isFullTime: true,
    email: "ethan.brown@example.com",
  },
  {
    id: 6,
    name: "Fiona Garcia",
    department: "Finance",
    isActive: true,
    isRemote: true,
    isManager: false,
    hasOnboarded: true,
    isFullTime: true,
    email: "fiona.garcia@example.com",
  },
  {
    id: 7,
    name: "George Miller",
    department: "IT",
    isActive: false,
    isRemote: false,
    isManager: false,
    hasOnboarded: false,
    isFullTime: true,
    email: "george.miller@example.com",
  },
  {
    id: 8,
    name: "Hannah Wilson",
    department: "Support",
    isActive: true,
    isRemote: false,
    isManager: false,
    hasOnboarded: false,
    isFullTime: false,
    email: "hannah.wilson@example.com",
  },
];
